### ISSUE TITLE
Build does not get past wallet connect

### ISSUE THREAD

**Issue by TheShoes** [decentraland/explorer-desktop#215]
### What happened?

Everything works great in Unity. 
When i create a build though the web browser pops up to connect to wallet then just spins. 
In the desktop build it just goes to the Timed out screen. 
So i feel like the connection is not being made only in the build
this error keeps coming up when trying to connect
4/8/2022 1:41:09 PM|Error|<>c__DisplayClass71_0.b__0:953|One or more errors occurred.

Removed Metamask wallet to try to force log in as guest but still does not load

### Steps to reproduce

Create a build for windows from the unity dev environment

### Operating System

Chrome, Windows 10

### Wallet

Metamask

### CPU

intel 9th generation

### GPU

980TI

### RAM

32

### Kernel Version

its just left blank in the debug confic

### Unity Version

2020.3.0f1

**Comment by TheShoes** [comment]
this error keeps coming up when trying to connect 
4/8/2022 1:41:09 PM|Error|<>c__DisplayClass71_0.<receiveRequest>b__0:953|One or more errors occurred.

**Comment by TheShoes** [comment]
I think i can now get it to work... seems like i need to enable the web Socket SSL in the Debug Config

**Comment by kuruk-mm** [comment]
> Removed Metamask wallet to try to force log in as guest but still does not load

You need to enable WebSocket SSL to use play.decentraland.org. And to use it in Chrome, because we use a dynamic self-signed certificate, you should allow the following flag in Chrome.
`chrome://flags/#allow-insecure-localhost`

If you don't want to use SSL, you can use play.decentraland.zone with the port 5000.

When you open Unity, there are some warnings about this in the console.
