### ISSUE TITLE
Minimized launcher can't be maximized ever again

### ISSUE THREAD

**Issue by pravusjif** [decentraland/explorer-desktop#315]
If we minimize the launcher, it goes to the taskbar and it can't be opened ever again, we have to close it and open the application again, we should be able to maximize the launcher to finish logging in.

**Comment by xavi-dcl** [comment]
@kwspgoliasz could you please check if this is happening on both Windows and Mac?

**Comment by kwspgoliasz** [comment]
@xavi-dcl The issue still occurs as described in the ticket. The app launcher cannot be maximized from the taskbar after being minimized. The issue occurs only for Windows client with a reproduction rate of 5/5.

**Comment by 2fd** [comment]
The issue is ready to merge, but for some reason, the build pipeline has been failing since August.

Now users on windows can re-open the launcher with a click on the icon or with right-click usgin the menu

| click | right-click |
|------|-----------|
| ![Screenshot 2023-01-05 at 11.46.49.png](https://images.zenhubusercontent.com/5e3c030aa21fc98c7daa9b14/e8309764-d135-4307-9913-4e3daac54c95) | ![Screenshot 2023-01-05 at 11.47.14.png](https://images.zenhubusercontent.com/5e3c030aa21fc98c7daa9b14/f763fac2-283d-4f3e-8188-867ee1466506) |

## Suggested follow up

The current behaviour hides the launcher even if unity is not running. I would like to suggest that the launcher only hides when is minimized if unity is running
