### ISSUE TITLE
Integrate unity plugin AVPro Video free version to define if we can use it

### ISSUE THREAD

**Issue by pravusjif** [decentraland/explorer-desktop#325]
We keep having issues with video streaming supporting a lot of different video formats, based on [this solution plan](https://www.notion.so/decentraland/Desktop-VideoPlayer-Plan-502aaa53074940e3a8d56aa045d63fa3) we should implement a spike using the free version of [AVPro Video Unity plugin](https://assetstore.unity.com/?q=avpro%20video&orderBy=1) to see if it fits our needs, and if that's the case we should device a way of injecting that plugin license in the CI to avoid exposing it on our open source repos (that implementaiton would go in another issue and not part of this issue's scope)

### Acceptance Criteria
- [x] Integrate AVPro Video plugin so that it's used to play scene videos and stream videos
- [x] Test the new implementation in several deployed scenes to see if it fits our needs

**Comment by dalkia** [comment]
Solves streaming issues in -118,120

**Comment by dalkia** [comment]
The following scenes play video succesfully, same as in Web:

- Filmrare (2,55)
- Notus Finanse. (-22,37)
- DG Arena. (-118,120)
- Wilderness. (-24,89)
- Art week.
55,61
58,60
62,61
66,62
61,66
54,64
61,70
53,73
64,70
69,65

The following scenes have issue replaying video, but looks like its more related to the scene than the video streaming. Further investigation is needed:

- Metazoo Intl. Boat House (110,-23)
Audio loads, but does not play as in web. The condition checker running indeed considers that audio should not be played. None the less, audio plays in web.
- TheBlock (-17,-122)
There is a event announcement video inside the Theatre. That video, for some reason, does not appear to be loaded in desktop; instead a stream is loaded that indeed works.
- Metaboralis inside art week (55,65) 
Causes plenty of issues due to a large amount of videos, and the reloading of them when one doesnt work.

**Comment by dalkia** [comment]
AVPro is not supported in Linux and WebGL
![image.png](https://images.zenhubusercontent.com/62a9e908660cd151471c312d/e502eebd-96c4-4170-9511-a365f1a8ca56)

**Comment by dalkia** [comment]
Waiting for legal to decide if we can use the license
